BARE-1:  init project structure
bareguarana/auth-api pull request #3
Opened 2020-03-15 18:51 UTC by richardpassos01

2020-03-18 02:28 UTC, 7odri9o commented on package.json
> +  "main": "index.js",
O arquivo index.js não existe e o arquivo que inicializa a aplicação é o server.js pelo que entendi.

2020-03-18 02:48 UTC, 7odri9o commented on app.js
> +    bodyParser.json({
A lib body-parser pode ser removida se utilizarmos o express que teve o próprio body-parser empacotado e entregue junto com express a partir da versão 4.16. Então qualquer função que utilizamos do body-parser pode ser utilizada no express. Até pouco tempo atrás eu não sabia disso. :)

[express.json vs bodyParser.json](https://stackoverflow.com/questions/47232187/express-json-vs-bodyparser-json/47232318) - Stack Overflow
[Express Release 4.16.0](https://github.com/expressjs/express/releases/tag/4.16.0) - Express Release History
[Express API Reference](https://expressjs.com/pt-br/4x/api.html#express.json) express.json()

2020-03-18 02:52 UTC, 7odri9o commented
O Arquivo package-lock.json não foi commitado. Devemos adicioná-lo?

2020-03-18 03:02 UTC, 7odri9o requested changes
Bom começo para o nosso projeto. Parabéns! Sugeri algumas alterações neste PR. :)

2020-03-26 23:33 UTC, richardpassos01 commented on app.js
> +    bodyParser.json({
Caraca tbm não sabia hahaha sempre inseria ela

2020-03-26 23:34 UTC, richardpassos01 commented on package.json
> +  "main": "index.js",
Haha vdd, criei com o npm init e veio default, esqueci de remover

2020-03-26 23:36 UTC, richardpassos01 commented
Curti o review, ainda nao fiz as modificações, quando pegar no pc denovo altero, muito show

2024-10-12 15:02 UTC, closed without merging